### ISSUE TITLE
Upgrade sqlparser-rs

### ISSUE THREAD

**Issue by yuval-illumex** [wseaton/sqloxide#102]
As sqlparser-rs released a new [version](https://github.com/sqlparser-rs/sqlparser-rs/releases/tag/v0.14.0), Is it possible to update sqloxide?

I'm looking forward to try the new version :)

**Comment by wseaton** [comment]
Sure @yuval-illumex, I'll try to get a release pushed out today!

**Comment by yuval-illumex** [comment]
Thank you very much!
