### ISSUE TITLE
Upgrade sql-parser to latest?

### ISSUE THREAD

**Issue by yuval-illumex** [wseaton/sqloxide#259]
sqlparser-rs is already on version v0.47.0

any plans to upgrade?

**Comment by wseaton** [comment]
sure, I can cut a release in a day or two :)

**Comment by yuval-illumex** [comment]
@wseaton waiting for it, thanks!

**Comment by wseaton** [comment]
delayed by issues with the macosx toolchain in CI, hopefully I can get to this soon!

**Comment by wseaton** [comment]
Thanks @yuval-illumex! This should be closed by the release coming up shortly ref: #261
