### ISSUE TITLE
Support lower macOS versions

### ISSUE THREAD

**Issue by choco** [wseaton/sqloxide#31]
Hello, really cool library! Right now the provided wheels require users to have macOS 10.15, would it be possible to set the deployment target to a lower version?

**Comment by wseaton** [comment]
@choco thanks for your interest! I'm currently using the [macos-latest](https://github.com/actions/virtual-environments#available-environments) environment from GitHub actions. It looks like 10.15 is the lowest available supported version, so I can't go any lower for native builds as I don't own any mac hardware. 

Are you having any issues building the library on your local machine?

**Comment by choco** [comment]
I'm not having issues on my local machine, but I've had reports from users of having issues installing a library that uses sqloxide as a dep. 

I'm not an expert with `setuptools-rust` (I've only used `maturin` for other rust bindings) but it seems that it's possible to set the deployment target on macOS through an environment variable.
Here's a snippet taken from the setuptools-rust repo (they also seem to be using macos-latest) https://github.com/PyO3/setuptools-rust/blob/61b0603ba8cecaff34331904de8f2a0d035152ca/.github/workflows/ci.yml#L86
Do you think that something like this could work?

**Comment by wseaton** [comment]
@choco thanks for the feedback, switched back to stable since we aren't using any nightly features at this point. Both pythonize and py03 work w/ stable Rust.

**Comment by wseaton** [comment]
@choco can you try the new universal wheel published here: https://github.com/wseaton/sqloxide/releases/tag/v0.1.11?

**Comment by wseaton** [comment]
@choco awesome! When I have time I'll probably switch this project to use `maturin` since it simplifies things a great deal. Glad it works.

**Comment by choco** [comment]
@wseaton I was able to tests it today on some older macOS versions and it installed correctly 😄 I guess you can push an new release 🚀 
Thanks for the help and the quick responses!
